"""create human reviews

Revision ID: f13603251c57
Revises: 87cea1deb586
Create Date: 2026-07-27 18:28:07.606499

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f13603251c57"
down_revision: str | Sequence[str] | None = "87cea1deb586"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "human_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("approve", "request_revision", "escalate", name="human_review_action"),
            nullable=False,
        ),
        sa.Column("reviewer_note", sa.Text(), nullable=True),
        sa.Column("revised_response", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_human_reviews_action"), "human_reviews", ["action"], unique=False)
    op.create_index(
        op.f("ix_human_reviews_agent_run_id"), "human_reviews", ["agent_run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_human_reviews_agent_run_id"), table_name="human_reviews")
    op.drop_index(op.f("ix_human_reviews_action"), table_name="human_reviews")
    op.drop_table("human_reviews")
    # ### end Alembic commands ###
